# Generated by Django 4.0.2 on 2022-08-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='my_employee',
        ),
    ]
