# Generated by Django 4.0.2 on 2022-08-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture1', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
